### ISSUE TITLE
Can I use this library on non core project?

### ISSUE THREAD

**Issue by vinnaykulkarni** [eyal7773/DotNetCore-DigitalSignaturePdf#1]

**Comment by eyal7773** [comment]
I think that yes. Try it.

**Comment by vinnaykulkarni** [comment]
Not able to access classes after installing package

**Comment by eyal7773** [comment]
So, you take the source this repo...or fork it.

**Comment by vinnaykulkarni** [comment]
Ok will try and let you know

Thankyou for reply
