### ISSUE TITLE
Error after Digitally signing the PDF 

### ISSUE THREAD

**Issue by VijayK1990** [eyal7773/DotNetCore-DigitalSignaturePdf#2]
I am getting an error after Signing the PDF using your code. Let me know the solution if any 

Code base for your reference
    string VirtualFolderPath = Server.MapPath("~/App_Data/PdfTemp");
            string CertificatePath = Server.MapPath("~/App_Data/Certificates/TestCertif.pfx");
    if (!Directory.Exists(VirtualFolderPath))
            {
                Directory.CreateDirectory(VirtualFolderPath);
            }

            Signer _sign = new Signer(VirtualFolderPath, AssetFilePaths.Java.JavaEngine, Server.MapPath(AssetFilePaths.AssetFiles.JSignPDFJar));
            string _BaseFileAsX64 = Convert.ToBase64String(System.IO.File.ReadAllBytes(fileName));
            string _SignedFileAsX64 = _sign.Sign(_BaseFileAsX64, CertificatePath, "12345678", "");

            string FileName = string.Concat(VirtualFolderPath, "\\", new Random().Next(0, 99999), ".pdf");
            System.IO.File.WriteAllText(FileName, _SignedFileAsX64);

            byte[] FileBytes = System.IO.File.ReadAllBytes(FileName);
            return FileBytes;
Please let me know if any changes are required

**Comment by eyal7773** [comment]
Dear @VijayK1990 
1 - It seems that you passed 3 parameters to the constructor (Signer)
the 3rd pararmeter  - it is not as I showed in the example.

2 - You did not mention what exact error do you got ?

This issue will be closed. If there are more details please open new issue.

**Comment by VijayK1990** [comment]
We have customized your code to suit our requirements, rest all of your code is same.

We receive any error cannot load document

**Comment by eyal7773** [comment]
If you look in the private method "signFile" you will see the command line parameters that needed to sign file from the cli.
So I offer, that you will try to check if after sign the file from command line - the file still open ok. 
Hope this will help you.
